---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: halbert
  namespace: halbert
spec:
  chart:
    spec:
      chart: halbert
      version: 1.x.x
      sourceRef:
        kind: HelmRepository
        name: jonfairbanks
        namespace: flux-system
  interval: 30s
  targetNamespace: halbert
  values:
    replicas: 1
    minAvailable: 1
    resources:
      requests:
        cpu: 100m
    slack:
      secretName: "hubot-slack-token"