---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tetris
  namespace: tetris
spec:
  chart:
    spec:
      chart: tetris
      version: 0.x.x
      sourceRef:
        kind: HelmRepository
        name: bsord
        namespace: flux-system
  interval: 30s
  targetNamespace: tetris
  values:
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
      targetCPUUtilizationPercentage: 75
    resources:
      requests:
        cpu: 20m
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: tetris-tetris
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: squaredrop.io
          paths:
            - "/"