---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rcvr-api
  namespace: rcvr
spec:
  chart:
    spec:
      chart: rcvr-api
      version: 0.x.x
      sourceRef:
        kind: HelmRepository
        name: bsord
        namespace: flux-system
  interval: 30s
  targetNamespace: rcvr
  values:
    podAnnotations:
      linkerd.io/inject: enabled
    dbHost: rcvr-rcvr-db-mariadb-primary
    redisHost: rcvr-rcvr-session-cache-redis-master
    relayHost: out.rcvr.io
    relayPort: "8587"
    senderDomain: rcvr.io
    websiteDomain: rcvr.io
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
      targetCPUUtilizationPercentage: 75
    resources:
      limits:
        cpu: 500m
        memory: 750Mi
      requests:
        cpu: 50m
        memory: 100Mi
      
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: api.rcvr.io
          paths:
            - "/" 
  valuesFrom:
  - kind: Secret
    name: "rcvr-api-values"