---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rcvr-db
  namespace: rcvr
spec:
  chart:
    spec:
      chart: mariadb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 30s
  targetNamespace: rcvr
  values:
    architecture: replication
    primary:
      persistence:
        size: 5Gi
      pdb:
        enabled: true
        minAvailable: 1
    secondary:
      persistence:
        size: 5Gi
      pdb:
        enabled: true
        minAvailable: 1
    
  valuesFrom:
  - kind: Secret
    name: "rcvr-db-values"