---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rcvr-dmarc
  namespace: rcvr
spec:
  chart:
    spec:
      chart: rcvr-dmarc
      sourceRef:
        kind: HelmRepository
        name: bsord
        namespace: flux-system
  interval: 30s
  targetNamespace: rcvr
  values:
    dbHost: rcvr-rcvr-db-mariadb-primary
    redisHost: rcvr-rcvr-session-cache-redis-master
    autoscaling:
      enabled: true
      minReplicas: 2
  valuesFrom:
  - kind: Secret
    name: "rcvr-dmarc-values"