---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rcvr-session-cache
  namespace: rcvr
spec:
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 30s
  targetNamespace: rcvr
  values:
    auth:
      enabled: true
    master:
      persistence:
        enabled: false
    replica:
      persistence:
        enabled: false
    replica:
      replicaCount: 1
  valuesFrom:
  - kind: Secret
    name: "rcvr-redis-values"