---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rcvr-smtp
  namespace: rcvr
spec:
  chart:
    spec:
      chart: rcvr-smtp
      version: 0.x.x
      sourceRef:
        kind: HelmRepository
        name: bsord
        namespace: flux-system
  interval: 30s
  targetNamespace: rcvr
  values:
    dbHost: rcvr-rcvr-db-mariadb-primary
    redisHost: rcvr-rcvr-session-cache-redis-master
    smtpHostname: in.rcvr.io
    smtpAllowedHosts: rcvr.io
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
      targetCPUUtilizationPercentage: 75
    resources:
      requests:
        cpu: 20m
  valuesFrom:
  - kind: Secret
    name: "rcvr-smtp-values"