apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus
  namespace: grafana
spec:
  encryptedData:
    password: AgB8dLtyUmW01fqqWVoOKgDHvl2f5uiXjiKw7PFUhje/pP6uRgWYtqPVTB/UQQxUjiyxIgxDBvX07vt3boSgKzToxYQ5BPfOANk/31j68nRRKLyTT+g8Jk9xJgYX2zXbJ1zuX+udlba459PdjGXpCH5VYImjiyXlsQw3Ecsjk0I4N6HlCNLoxDYPB8iVet0D43R639oSshMvAwY791emEuvDuSWAA8rKHK+QHB3gTM+HzatYrzF0T+azUobUesRxPjvSBlab/0f1VvzdNpefb/peEeb7YRAgShzT+ede3F8t6wfez2a3WC55A0bsCTsyBtV26t5iKM5s1Rp5yXBZM3LHf31o7gJWdTJAugC8Kkp6RPx6Ya4pD4YmKXFvaz1iNpcb6OYRXXqWpZipuXqxE7Qbxz+6VKeWvJNvDjb5fcTp9aYCwgxzVGJBZu7YeuFVqMzVUVLKr52dDJsHDK9E4o75Mp5n8dyV861tq2N+kojZ2fNZj/NTWZCbhD3f4ZHfI9f7Qnu+CGguj1NV32B9xObecIaV8Gasbfm7wnU3KbOd/tQrVIzXE27JATIejbe3JZf03JzYetH6ROhIGUaVzbOTtT/lTawIMO3EY7lApqeELAk+54prYBu4SppdsIqmBor6AgCMU063lVR/EkeVA/5ZFUQd140tFdpFIYA4+zHy6DhE4uGX4qvBXSVn2ee4myvfGfJKMte1PCn16gBGHVJ7nNRCXqFV/nNuHGnszPp5tjxbb4BVzsZbQLJ4lDQq+ZxR4AgYXQN3r0RjYNsSnca9nCtPCLdanWjX/C33hrtt3YVFpSyVhNKYbfsAjRjMLOSzcKv2vV5K+A==
    username: AgCNkzryNbkSJqh3Q4yXSIMojXVt1j/Znlhcwt1Qz58J4LG8++6UASTjcfPBJmz2QFsDQ0w7DdOuOWwopjwzRGG+5ytBB/xZUGZMA/Uj5jEabVuQtRqVaaSB2KxMED5frHV+GodSIUVRpiibCc5cq9QczZcCWkq1Pt+1ksEoQtz0XXsnXyPMHCOUFFlYxoZAlO1I28yjHzqXX5nrjStRwfYKRDhBwMN/YsSZgZ13nMRHBLBVluT1TvrfQ9WiJA9uYl8JrDoDJLSxPUqE5ZRHFpc42da7vPJsvvR5rikEjWnDD47NdWIRWiX7k/j3ulIJtJlH9xChZX6uQDyqv+ZT1pmZXLCW5F5uLmhLOR8I55ATXs+VYn7rccr8R4tvIafGkeTBhAmmd7UdOs/ZLP+FtJE4jaoXg4HWrMBSUX+OWAdKWnvHfjhUJAe7C+Ir5Yxj95TCVnaT0dMfdtx3wYmG2qptNpN9xNMACkbFw7n+U3KykWJ2f0jzWBI4PU6keByYXVq5IZLwx/rf9e1cbHNfUaBe2bjvqKw/TjkavD8qmxq9coV1048R1pIis5PH1Koroaqxwc9OZqKlm7gf9+Jhgvbm8gOHzHv9R7jAIqWRh1B8ZL2oMik+uiuXYZnfKY9fLZVzmfHS8AjdnjLcwi9NI4SbRg8RtgrZIsMJj0byMfhQwDWEuuNsDW5J2hHejDP4QUx1rg8QLSY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prometheus
      namespace: grafana

