---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-agent
  namespace: grafana
spec:
  chart:
    spec:
      chart: grafana-agent-operator
      version: 0.2.x
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 6h
  targetNamespace: grafana