apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: f5oclock-scraper
  namespace: f5
spec:
  chart:
    spec:
      chart: f5oclock-scraper
      version: 1.x.x
      sourceRef:
        kind: HelmRepository
        name: fairbanks-io
        namespace: flux-system
  interval: 300s
  targetNamespace: f5
  values:
    secretName: f5oclock-mongouri
    subreddits:
      - "politics"
      - "all"
      - "worldnews"
      - "CryptoCurrency"
      - "news"
      - "AmItheAsshole"