apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: f5oclock-mongouri
  namespace: f5
spec:
  encryptedData:
    mongouri: AgBjA0NptbJbM4mUkDsn1F5ZRPRDL0ifF0kzyHniqVUkRYPa07fHvjrJhifCv6hksChomo8BdnSdlAZpBob5pUTCqpA5nzEC5DQvsQ01WUnJuajOu60yKeXwbshKX+HODKraU/OvJYmzYggzLGDiEjx/LSYt2NNykm1BB+DyEAlot5p5UY0DvQBJwpezo+4vrVYHd6j9+S5gixbUjMNWAjth8znb/mSXUel2pyAsrdzJt9G2YKvPpjd16qLKxV471gCM5yBNvsgg5eRtHFwTXu3h1E08Nr+YTxclnX+civZILQB3d19p1nlBjybyH1ltUoRZ1fqEIxECWa5HdefaqYMNOWtiTpDpsj8+zSRYI5jefHRqS3mWdd4qNNq1QiWJWGQNnP4VOPr1h0TRiN+y2g7/pjZIupOjSeZfY3FmUjVYIHFJ3Dz3kAh5rLtZQfxTEnYyrvGq31UVRb8g+4QFciVhBb3xvdcGD9KzRuUdgDnHiMzEVoaHEqBxDOKzIDaiv9RLWkCYAJTso/AVMV4IWd7mcxeDqnsQEHqgzeTrDPTnnz+h/HJLCUsr9TXBWENhFyygnUGjqvLh60s7cd8r8bcPkFg8KljoTxLGPgVKNUbT8BAWrGfxtP3/i8n6yS6+5yOKcdNUatjsekAgmjYxvPW16T4HcbG31p1cxuTLKuRWrhgREEpXhiKAG1vDksWxFcH3GBk7oSLDNvMcUDSbAGyTkS4/3AHr1lPN1E1t/pVy0jnjdoW+m4FKZaRTgkkUendzJff46rSvpRiMLO/cxX8qNzIMqMthCxqDn2zIWwi+pvd6oojK9aYQ/YbGt6rRpUUPQ1fuJnoyWvfO
  template:
    metadata:
      creationTimestamp: null
      name: f5oclock-mongouri
      namespace: f5
status: {}