---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paypal-sandbox-dashboard
  namespace: paypal-sandbox-dashboard
spec:
  chart:
    spec:
      chart: paypal-sandbox-dashboard
      sourceRef:
        kind: HelmRepository
        name: fairbanks-io
        namespace: flux-system
  interval: 30s
  targetNamespace: paypal-sandbox-dashboard
  values:
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
    limits:
      cpu: 100m
    secretName: sandboxsecret
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: sandbox.bsord.io
          paths:
            - "/" 
        - host: sandbox.fairbanks.io
          paths:
            - "/" 