apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uptime-monitor-secret
  namespace: uptime-monitor
spec:
  encryptedData:
    mongoUri: AgACcT3mSAyQWLpmVNP9VTL1JhsQeMG2ctvVFs/z+aWEKsGKA2in8IkWqWbnV10V5zqYFCV1a9X0aT/oA6siowofEBFErdDxlxEEdSO86tYmldW9c6dlMcYIBuEasA+nV5jPThzVxiyCG+k6QQAf4/EZYWGk4/v68pgj8skq0bw1iINBRu1eHwOPq9kzmuy4Kfhb3+mra9olG84QZX3aIANDgAYWYqJ4UQ1Z5wyE2j/IirL6qxoir2vAO3rWccmYVPCo4ZdpPR3oaVzjEB42g2SMSquza3gZYs65LTiXaEX8iha9AdZ2CEGE5OhHpLsKtNVsYP425YuoFBwNcUtoxawiGq9IZHMkTEdHL1shpFbG1ixkCFXfDT/FilvN/SMDFbuRdtV+37E2at5UfNS67nHmkRhoDgUxNs+XRFWH4IW0F47Jk0mYUUWSbdtkC6T/DgxHSOK3p5tXh6jDVLE2nAgY1EuzNGge7gS+eWJZcSbLZH2wqrv0FJEvD1qTHZ5RqW6TG1TeiuSJkZsviTt5iPrXKlW3AsULDCalsf964pfwxH3MD+kySds8gyX2Sol8iF5ywA1Em/zKTEOkRJ1UX4IZru8y8GCazp5oS58geW7kCE7zBpJ1K9rd6GjUb312Ebx5NkdQKJ5mdvhkdrUmj8Ar4Zy9X4BzunxvYQch+sSkM4w2kZf2R6v44pdfOsWuMM+0YtXeSx6Dq6uP0RppJr5Gg9i8Q8GhX7dl0RmKjJoGg+X/iCr7Py9ofsk3ACAGjBkS99tH64KKIzyUvthyEqPZm8RFvKETeiGOPx2cLqiliKUSKS1R8HVo5FJroIP8VDpPtOSR7I4Lx/rxSpEl/JtNpw==
  template:
    metadata:
      creationTimestamp: null
      name: uptime-monitor-secret
      namespace: uptime-monitor
status: {}