apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: factorio
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://sqljames.github.io/factorio-server-charts
