---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: default
spec:
  chart:
    spec:
      chart: metrics-server
      version: 5.x.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 6h
  targetNamespace: default
  values:
    hostNetwork: true
    extraArgs:
      - --kubelet-preferred-address-types=InternalIP
      - --kubelet-insecure-tls=true
    replicas: 2
    pdb:
      create: true
      minAvailable: 1 