---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  interval: 6h
  targetNamespace: kube-system
  values:
    hostNetwork:
      enabled: true
    args:
      - --kubelet-preferred-address-types=InternalIP
      - --kubelet-insecure-tls=true
    replicas: 2
    pdb:
      create: true
      minAvailable: 1 