---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jonfairbanks-homepage
  namespace: jonfairbanks-homepage
spec:
  chart:
    spec:
      chart: jonfairbanks-homepage
      version: 1.1.x
      sourceRef:
        kind: HelmRepository
        name: jonfairbanks
        namespace: flux-system
  interval: 30s
  targetNamespace: jonfairbanks-homepage
  values:
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
    resources:
      requests:
        cpu: 100m
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: fairbanks.dev
          paths:
            - "/"
        - host: fairbanks.io
          paths:
            - "/"