---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jonfairbanks-homepage
  namespace: jonfairbanks-homepage
spec:
  chart:
    spec:
      chart: jonfairbanks-homepage
      version: 1.1.x
      sourceRef:
        kind: HelmRepository
        name: jonfairbanks
        namespace: flux-system
  interval: 30s
  targetNamespace: jonfairbanks-homepage
  values:
    replicas: 1
    minAvailable: 1
    podAnnotations:
      linkerd.io/inject: enabled
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
    resources:
      requests:
        cpu: 10m
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;

          if ($host = "www.fairbanks.io") {
              return 308 https://fairbanks.io$request_uri;
          }
          if ($host = "www.fairbanks.dev") {
              return 308 https://fairbanks.dev$request_uri;
          }
      hosts:
        - host: fairbanks.dev
          paths:
            - "/"
        - host: www.fairbanks.dev
          paths:
            - "/"
        - host: fairbanks.io
          paths:
            - "/"
        - host: www.fairbanks.io
          paths:
            - "/"