apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: f5-mongouri
  namespace: f5oclock
spec:
  encryptedData:
    mongoUri: AgAqSX4RVDRcMzIqERXjpdk4kh8yMofaUmYwVAc9Uo+hbnvL8OQ6c1fCHIIg7+7jnUi0Az/31s21U7cXW4UGKpBljQk9BijY64C1Qk7TGVbq2agX2Brb3yue++2dLmih2R30FK62/iqHYKxVJWNccAcVfT9QobW9V/2mjg6v74sHf1pg71FRFR2MGSaDYvhbuFS0o0K4PgGQdzNuNTk4eBVDVqvoKJZxcC/ZDMl3YDux0qvl74F58jj+NnY47iDKZ8aZbrHdYEMPHtlLxZ/630d538C2BiUXP5/vIvON32wE/btSTjSlhtkN3FLdLEhYzq3IF/iglqOIjoEuJSMPyGMtqH2PDYDLpqqH1WD5IkC5jwTpY1/3t7aSpMLxkKKQ+fDba+ayFxwLiwCK1kaNkgAdpkojPYVIY06Ntd5haZB/zGrR6jGGhk9MXRyWuGuEcuA4VBG/Zl3IVpp/9Jeu91tedeY6b3CWWrMrnzv81xPDnFiQLDHFDHrFrpDOmODMg/tzuKWLpgBLQpvia5KpSGU+ebtOHGDtqrWnW8yRuf7HribB2Bft1ZtcGzF5YrvTqY8US6X0bu0CSWiAzmnZlPPsPWyttlC+P2iop3ITwpXHpY9eR0+hORDVQ5cpN3xII+ktmO89sf/mSxSpF+cS9groT1PqXVXeVfIpuv/pDVKnsoVk/8IQsVc55eyqY04GtwnwEESd5g0QqeYyRuytLPVcvaJpvHopIX+bBUMxc8Nb8jwL1AdNuVsTakD1pd6IGda5/cq8DVNwqXcfDXv+S1TVOMFSHYzOAbB2esqB4xynfF96W03kc6fVRvMFYleUn9693LlMaPQNmDyJm+3DTK7xWQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: f5-mongouri
      namespace: f5oclock

