---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: f5-api
  namespace: f5oclock
spec:
  chart:
    spec:
      chart: f5-api
      version: 1.6.x
      sourceRef:
        kind: HelmRepository
        name: jonfairbanks
        namespace: flux-system
  interval: 30s
  targetNamespace: f5oclock
  values:
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
    resources:
      requests:
        cpu: 50m
    image:
      tag: 1.0.5
    f5:
      createSecret: false
      secretName: "f5-mongouri"
