
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: f5-web
  namespace: f5oclock
spec:
  chart:
    spec:
      chart: f5-web
      version: 1.1.x
      sourceRef:
        kind: HelmRepository
        name: jonfairbanks
        namespace: flux-system
  dependsOn:
    - name: f5-api
  interval: 30s
  targetNamespace: f5oclock
  values:
    f5:
      secretName: "f5-mongouri"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: f5.fairbanks.dev
          paths:
            - "/"