---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: markdown-editor
  namespace: markdown-editor
spec:
  chart:
    spec:
      chart: markdown-editor
      version: 1.2.x
      sourceRef:
        kind: HelmRepository
        name: jonfairbanks
        namespace: flux-system
  interval: 30s
  targetNamespace: markdown-editor
  values:
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
    resources:
      requests:
        cpu: 100m
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: md.fairbanks.dev
          paths:
            - "/"
    podAnnotations:
      linkerd.io/inject: enabled