---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: kubernetes
        namespace: flux-system
  interval: 1h
  targetNamespace: kube-system
  values:
    rbac:
      create: true
    controller:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 3
        targetCPUUtilizationPercentage: 50
      limits:
        cpu: 200m
      requests:
        cpu: 50m
        memory: 200Mi
      service:
        name: ingress-nginx-controller
        annotations:
          service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: true
      publishService:
        enabled: true
      config:
        stream-snippet: |
          server {
                  preread_by_lua_block {
                          ngx.var.proxy_upstream_name="udp-factorio-factorio-30000";
                  }

                  listen                  30000 udp;

                  listen                  [::]:30000 udp;

                  proxy_responses         1;
                  proxy_timeout           600s;
                  proxy_next_upstream     on;
                  proxy_next_upstream_timeout 600s;
                  proxy_next_upstream_tries   3;
                  proxy_pass              upstream_balancer;
                  
          }
        annotation-value-word-blocklist: "load_module,root,serviceaccount"
        use-proxy-protocol: "true"
        proxy-body-size: 250m
        client-max-body-size: 250m
        proxy-connect-timeout: "60"
        proxy-read-timeout: "60"
      affinity:
      # An example of required pod anti-affinity
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: kube-system-ingress-nginx
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway