---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tiles-api
  namespace: tiles
spec:
  chart:
    spec:
      chart: tiles-api
      version: 0.x.x
      sourceRef:
        kind: HelmRepository
        name: bsord
        namespace: flux-system
  interval: 30s
  targetNamespace: tiles
  values:
    redisHost: tiles-tiles-session-cache-redis-master.tiles.svc.cluster.local
    tracingURL: http://collector.linkerd-jaeger:9411/api/v2/spans
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
      targetCPUUtilizationPercentage: 75
    resources:
      requests:
        cpu: 20m
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:3000;
      hosts:
        - host: api.popcan.io
          paths:
            - "/"
  valuesFrom:
  - kind: Secret
    name: "tiles-api-values"