---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tiles-api
  namespace: tiles
spec:
  chart:
    spec:
      chart: tiles-api
      sourceRef:
        kind: HelmRepository
        name: bsord
        namespace: flux-system
  interval: 30s
  targetNamespace: tiles
  values:
    redisHost: tiles-session-cache-redis-master.tiles.svc.cluster.local
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
    limits:
      cpu: 200m
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: tiles.bsord.dev
          paths:
            - "/"
  valuesFrom:
  - secretKeyRef:
      name: tiles-api-values
      key: tiles-api-values.yaml
      namespace: tiles