---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tiles-client-dev
  namespace: tiles
spec:
  chart:
    spec:
      chart: tiles-client
      version: ">1.0.0-0"
      sourceRef:
        kind: HelmRepository
        name: bsord
        namespace: flux-system
  interval: 30s
  targetNamespace: tiles
  values:
    apiHost: api.popcan.io
    googleClient: 963187711576-5mbd7l390n34lj43cpfar9ustlgfemi7.apps.googleusercontent.com
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: false
    resources:
      requests:
        cpu: 25m
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: dev.popcan.io
          paths:
            - "/" 