---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tiles-session-cache
  namespace: tiles
spec:
  chart:
    spec:
      chart: redis
      version: 14.8.8
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1h
  targetNamespace: tiles
  values:
    master:
      persistence:
        enabled: false
    replica:
      persistence:
        enabled: false
      replicaCount: 1
    auth:
      enabled: true
  valuesFrom:
  - kind: Secret
    name: "tiles-redis-values" 