apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tiles-api-values
  namespace: tiles
spec:
  encryptedData:
    values.yaml: AgBLh4wTFPU+qXN/n8nx52RBqZsQ2AJX9/9ohXvHXg1QgRHoxitb/yksXNEdTRAlLBs9snL92RzjzBxibU21K14V80e2c3ubeAvc6AUvXm3PHh6h4lZ2+dMBiRRfzr3xVHgw532bEqvr4zCGtbJmWeLFDKC5oo6UOY68GOMnQZljmmVmJzJgfnzzw2Q8Kjz+JoWTrYC0Xvu7SAH3f7wlU5ivtx0vqdNuZbLQQ4Pe3fj3DG+71w2zMFP2eWziOhAQQwTlO0GNP4X94D7S64sSzsPAR+qkd2YlW6/wiqhk1BYkJ12u8FdUKxo5L/Ez53cK7iqFkqAvQIgQu1yCNUmrsde/voI3r3Nj1GXcnJqgogbuobb96D43WAzcNCET3y9uqmuY6fxcO12jRbmTb7JFhxjvtivhexjOlrinZwAE2KLZrNmitXropuaOPwivAF03GWgLNDPeiqgcX+a1AIBwMu2BIxl8AIbBQc/Vrg0waKacV/zP/VcNK8jB4aeBaCs8E0X80QwjW1154ndeWZ5+cOYyKvvbm+9Fa/NqtiHju6hq2lQNaBmnq6EAm1zMQOZfPHNXryo/aT025CvTUli7m16e4J0pX+kWcRMeKZdtRZB4CEYCaTZPykeFSocfc1oY7lRgAw/OUp5v77cFG0zq3l4oe9cBTJMDR6fSlgMwthFRlvwIVt5LlyNtHJLY8LwZmXRwhOhhVbl6gsdn607cjHvWxcyqO6Q2LSlY5cLc2ZTGyoocJTdbgAZ8qhcQISFoDko2Bfkrayap+pC+1yTLlO+rJNnTAjxq9CRd4Ma86++dRBJ3W1bC8QWfexH9C5OzWVvkxFYXbDxElrOzGMjLrz2JRkoSWSjy1xjjHUFu6DdMATxvpwexQnQ1d3Z8WcWm8faGZNL9eOfiE1yCNhK5DNUK4KJYK80XLrcKPGOCl1jo6zOqLBeGuotb6eVLU38SaEuHTzdZ1bQGZ00+oxIpTgdDGbsgEO6K0Bi8nrwQ2XOQ6YLRCFVkzVHWq8kMJ5RAfvBrqeQ/BlJo0Glm38DiCGzmUG45z4gGqDqOGJ8ekaoBAg==
  template:
    metadata:
      creationTimestamp: null
      name: tiles-api-values
      namespace: tiles
status: {}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tiles-redis-values
  namespace: tiles
spec:
  encryptedData:
    values.yaml: AgAoaM6uluH4PDuKIrV5HTqwZPZDWKT5jRfNtrl5Qmw8bjyeib0DJtA/3kUYypaSwN/3pGsUPF+ub//wPOsBYzXaUDezaBhkQxXwwvhd8UyfzjXFetxEZV4B/gTDuBcxkFEf4tur/6Kzoe6q1e9TliWZWFsme9dqqW06wsvbH5NF3FyHNoBNrPTfxViHENblZbNhLHfTHTNqiHT+czbCfOLQos5M9Z0XUffZF1i2k/z/KJuKHx6oRyAgcwjUBBwrwmr+Fwem26tNUViaBoLtbv7u4d8CnXiOA1VN3zcz+hF4wSzGXcYUG0ycsfEHdpwvXGOWeSfDWNJ1xgtXsJiOG0qGiD2NCVFIl0Y36Zl+6rZxca2VIav8ITUDPf6oVEjf4/nlFrJ0iSH7cOm9ZJpz4vjusO7QUxrvvQaYlu0HDk2AWW8qsJ/VWkG8fBKFn9INz8gFpZb/iu9ZyWWsFsRfKoASQLmIdzR5rIU7+tyb48TRhY8/WFn5FJO7oxd7JZ8lxgjvHe/lMlElH5M4Lb28QqmW/CoNb6rwdClFvHFWsf5nf43iTCkGurE7v6CLvc5kgVs0j27thqC3mb0Gdrj/jdODehiruNnBGPU18TDdePxf0ywCsKETOmK5mVH6jBZq1ksPg969msmktVVZqLNYJLQyEBZJtN7XZt5rkKIZSAJlP4xr1OhTGElLUlah0VRxzcujdkxCTewYTMkBUUMekuYheVi2PHhocCTVQ+uAMk/yDg==
  template:
    metadata:
      creationTimestamp: null
      name: tiles-redis-values
      namespace: tiles
status: {}