apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tiles-api-values
  namespace: tiles
spec:
  encryptedData:
    values.yaml: AgAQ58PTvUbG9yD8P2lbHjM45r25cuzm0xFnRvTasx77ucJgR/t2ip49/U3giEoirj4nb0uoXhFNhZLqvD9IVV3LkN8g3/lGOY4Zl+E16HPTAfRp2hin0TJGmF/qOD80e0O0b7Z1cA6HEGkZcBYn+TU8kfU4g4udZkrmExTITpd8S8DAu6hbLyXkIuIzUurbKDr0Uwbk99nN8mr2RpWjSTLv3dBOXc/pNDEp/Z2Cd4c2Ax8WF+AUpIrfwtoKQuEgUKcoRh/ulRG1uZdpmSK/DYXzqvyxjyLbBJFU/e56q0+VutGLUmOYH+j6a/sVQ04J9xZk9Kh/kwZgQzJsHHZEKokbbyalRt12kUzPmeXCRbuJpnmpqNrdWxtPllDQ7xCacDwlcSCXXS1QQbLe8iMASmiu8ryAkjk9sBGM0uJLDXJyoF82cWePJ6Y9pCni8QchqVGR0GCq4WibiJ1CCrQVwp4/eypyegXmTJaw+JnVYc0MtT3E817iMfO4rPvqre0CdMtYDempHlf3ifNSHKf63SzacLCDne1r5Ky7DwMgei9ojbhtFmOwDLoXNiSyVBa5mQkehlAxNtjenqGQp/erbhM84i0DFE2rcKKo0eq3zPMqdBp38oZtD3XiEUDADEYiuJ9Epn25XVxPCsU9Uvl401bhQ17t+PGPm9+JkxS2+IFnXQ0ife0aO7GRvV/FPDxOysnSKiGnb378E6rIyyINFn7nIAFOLFCUeq/ofbYa5aEEk9XJsoBOjdxnXV9p62NEMhTnk1J5o/I79kAifgRIUYfDKTBPQgSQopHv4zQUHPdQeGX3/JRkm9RSZdUPaTMlh5S00yf+JSOPTg3n8SSqOnwx2S1Fv6QzaUDXi7MEBczsh7j0RSF7HSYLVE9MGzudillfgrUz1A==
  template:
    metadata:
      creationTimestamp: null
      name: tiles-api-values
      namespace: tiles
status: {}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tiles-redis-values
  namespace: tiles
spec:
  encryptedData:
    values.yaml: AgCVkWxhE1dg4ufuIfxL2teYoGF7C/NZAhTayt/Bnbv7jdHaUaj3gsrvckZ5w6P6MRWaNUrViCH34JskTqhAjakjrITlOD/6s2AASXVDd/UH/RIj0DHrc1h9pOHjt9b9yaX5ZzPZX9uXH8b8KQrGnO1NXQfJULYPfriJNyWzqE4FLWR0mhcN0/prEfH6Y4wnSS6xK01lvITgfP5lrmzeuXJLTXiJ+Rq0L0hcu9cja8TvgnkUeWTjYyDsp0hpdAkgXBvCl0rmTOhb0CauP/mCDWdLxxu2bveVefEXNFj8z5CeFxEkshYvq3APygVQSJ43t12Ju6XAbTr8f0XbQTzTxbuAS2aePknsOYByE87DszsxDCH7dT5WIT/b+LZrFLNAUst9VX4SEMaeAcKS3CRKncz+8KkKrJqJQupeoNd5MGQpQHMnu+WsiR5TXTN4PxWUkO1J07OwY36Gvk2MtC2T4H6uiguozaVnotwwYccDBwfoA85k03G0gXmj/fy9glUoOyhIak+102QWOJ2dHgChJWwffYEdndl23gBFYymX3ldvUnLaQ0Bqe75qrKZkrV5tM2ZRFN4U0YPR4UkEB38NbEPZQPh/lTa3i9r0YPLicWtMpJj+ajHXd1V5R47yHRH+j0HjN6QHPKMH98BN7DradlT00BHJJ6ibZ/1ZxPdZmPiKkSXvs5lvXiaHB2Z2yvo8zJ5iLlSPJx0a+fOPQlQgmujEywPQCGStBGo=
  template:
    metadata:
      creationTimestamp: null
      name: tiles-redis-values
      namespace: tiles
status: {}