---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: datadog
spec:
  chart:
    spec:
      chart: datadog
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: flux-system
  interval: 1h
  targetNamespace: datadog
  values:
    datadog:
      processAgent:
        processCollection: true
      apm:
        enabled: true
      dogstatsd:
        useHostPort: true
      networkMonitoring:
        enabled: true
  valuesFrom:
  - kind: Secret
    name: "datadog-values"
