---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: datadog
spec:
  chart:
    spec:
      chart: datadog
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: flux-system
  interval: 30s
  targetNamespace: datadog
  values:
    datadog:
      processAgent:
        enabled: true
        processCollection: true
      nodeLabelsAsTags: true
      podAnnotationsAsTags: true
      podLabelsAsTags: true
      apm:
        enabled: true
      dogstatsd:
        nonLocalTraffic: true
        useHostPort: true
      systemProbe:
        enabled: true
  valuesFrom:
  - kind: Secret
    name: "datadog-values"
