---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: datadog
spec:
  chart:
    spec:
      chart: datadog
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: flux-system
  interval: 6h
  targetNamespace: datadog
  values:
    datadog:
      processAgent:
        processCollection: false
      dogstatsd:
        useHostPort: true
      networkMonitoring:
        enabled: true
      agents:
        containers:
          agent:
            resources:
              requests:
                cpu: 100m
                memory: 150Mi
              limits:
                cpu: 100m
                memory: 150Mi
          processAgent:
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                cpu: 50m
                memory: 100Mi
          traceAgent:
            resources:
              requests:
                cpu: 25m
                memory: 50Mi
              limits:
                cpu: 25m
                memory: 50Mi
          systemProbe:
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                cpu: 50m
                memory: 100Mi
  valuesFrom:
  - kind: Secret
    name: "datadog-values"
