---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wp-test
  namespace: wp-test
spec:
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 30s
  targetNamespace: wp-test
  values:
    replicas: 1
    limits:
      cpu: 100m
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: wp.bsord.dev
          paths:
            - "/" 