---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: json-formatter
  namespace: json-formatter
spec:
  chart:
    spec:
      chart: json-formatter
      version: 1.1.x
      sourceRef:
        kind: HelmRepository
        name: jonfairbanks
        namespace: flux-system
  interval: 30s
  targetNamespace: json-formatter
  values:
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
    resources:
      requests:
        cpu: 10m
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      hosts:
        - host: json.fairbanks.dev
          paths:
            - "/"