---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-cluster
  namespace: docs
spec:
  chart:
    spec:
      chart: kube-cluster
      version: 1.0.x
      sourceRef:
        kind: HelmRepository
        name: fairbanks-io
        namespace: flux-system
  interval: 30s
  targetNamespace: docs
  values:
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
    resources:
      requests:
        cpu: 10m
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: docs-kube-cluster
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      hosts:
        - host: docs.fairbanks.dev
          paths:
            - "/"
        - host: docs.fairbanks.io
          paths:
            - "/"
        - host: docs.bsord.dev
          paths:
            - "/"
        - host: docs.bsord.io
          paths:
            - "/"