---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: f5-client
  namespace: openfaas-fn
spec:
  chart:
    spec:
      chart: f5-client
      version: 0.x.x
      sourceRef:
        kind: HelmRepository
        name: bsord
        namespace: flux-system
  interval: 30s
  targetNamespace: openfaas-fn
  values:
    apiURL: https://fn.bsord.dev/function/f5-get-posts
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: f5.bsord.dev
          paths:
            - "/" 