---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-bsord
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 4.9.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    sources:
      - ingress
    provider: cloudflare
    cloudflare:
      secretName: cloudflare-bsord
    domainFilters:
      - "bsord.io"
      - "popcan.io"
      - "squaredrop.io"
      - "rcvr.io"
      - "weatherdrop.io"