---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  chart:
    spec:
      chart: grafana-agent-operator
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 6h
  targetNamespace: default
  values:
    namespace: default
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"