apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: primary-credentials-metrics
  namespace: default
spec:
  encryptedData:
    password: AgAZThapFyuWZtRaIV4i42IKZ45q3gORVrsqaJoInXZnfwYgnL2chrDyQfhIqRPmpJKoSJH631F3CxawrNh/i9vvsnYw1B7FEcJl3cVfWJjJboAYh84piW3gpd2Gmz5+jPHtlBxvGMszjcpGANsEXX+tA1njQa8YQ1pVkywyTrudbjeZh5yhzmjyYFDL6bJ+ZwcNMPczAoS3dKlSuwxUIlgbqZMfpWoVrLRQMwtpO4GkL10RIQQpgM/8YkKvlhkgmfyHMRCuZkqMOuXJ54slG/vbbtoewm2UusWTD1r05g3XuwjymMDOCbHPN4AIGJWFnlsyi2eSv/IG1u8fUUpDkHTyi3LprH60bU5N4JrJmsYagOtvU+cCuWn+vZI+rfndDf414FfQsR9rI9iETfwrJ1o4WNYpXAg0dzbFVFdUJDDSDExj/Nf1EYHa3KthiMtdFKA5iczj6inxofoThDtLdUYyRIwyxyBMy8kr0QsWmz4ucFHwsu9V7osLPNJdUOqAnAImrocIel5yNBg3MqJo8ds+4RTpoqOOmXmdx0oAi1siKnyaMimn7W0BC7wizVm76MdCuE5IVBzJhBsgHQhmskIkGX2UOc7cLxUZwjlM/wHvjC7EOosEYsAdKSS+q3gQ/ZeL1W8kb3cvHInWdqqFDUXNT/vci3Lg/xRUylFH55P78DSVudj9oX+7gHncLeL1VD+QlSOK0HRLiulhuGYbrLk5OiOBeW25MxZOtIlmdxxBKjSbz5fYNKYcVnSZYAjigS8jHb8vjFiXok72FyrxzGpGeE13ORlzr8lIXQ/7hYJXft2Lah9T8j0gAi78+eN1kiMW+4VtIuQgpMSfiluK5fnEBSCzhQ==
    username: AgBcoINcNMUbyh9b91nKWPBRZtNtIg2H6amesMxNhnmbAGkZV8AHTx/o6cNOMvQkyIX9/4ZFSZ1HZvXGrxOeiytj4q+C5ddSMnTz5uAlbvxyWntAGqYwGJ39c7dKHNriIkdGQ4xn4VBvZoQ+3HC4oVhIcBiUJhhh4ELO70UqKSu9nqGQfzrn/kX3IpgvBpUVlHCmuS0ofyeWVfioJjyFakqiZygOnUNVqXZ2WEWSKb8qBPn8VxpJK4ui68R3DJtsHAzcTnYkGZI5jE4N7ozU+DeHqk2Y7EA+cL3y4e+GP7GuGR+/LmbNawf1zlU5FwbnkZ2nSsZbU3x/waJSVDQGBFkLgMn6PTpHeM1ern8HbcFBXtFTh/nDsqGOqF/RrqVFJpuCMaswqJTRnAxkhIdo7wLp2+RbJleLuyxnyicuGqOvTHJFbssdJYSBQ02g0WP1J3nEHfiAGmBA3T5Ef2SmTuYNeSR7OIQGs1bmyrYFY3ebnAE7cREvouEI5gUdhJDLVWw4Sai2ZE2q4Euem43FrMSCMHpktMvqE4yvmAK/n0Jqq11lb2JpUtbEhmOGUAyhNvVedax6yH6RsEWXjpNsMD6C5aeBxQWymwHSd1/ZNs+vh3eelRrI/D5v9Xx1zUqv8mJMIJEwOf2hUYPZK2lSWuy/TzQURYpvCHElerPt2FmXYzlTR2Zi+w887zqf/aEv9v3JlNlZEOQ=
  template:
    metadata:
      creationTimestamp: null
      name: primary-credentials-metrics
      namespace: default
status: {}
