---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  chart:
    spec:
      chart: grafana-agent-operator
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 6h
  targetNamespace: grafana
  values:
    namespace: grafana
