---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
spec:
  chart:
    spec:
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  interval: 1h
  targetNamespace: linkerd
  values:
    namespace: linkerd
    installNamespace: false
    