---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  chart:
    spec:
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  interval: 1h
  targetNamespace: linkerd
  values:
    namespace: linkerd
    installNamespace: false

    # High Availability config values
    enablePodAntiAffinity: true
    proxy:
      resources:
        cpu:
          request: 100m
        memory:
          limit: 250Mi
          request: 20Mi
    controllerReplicas: 3
    controllerResources: &controller_resources
      cpu: &controller_resources_cpu
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    destinationResources: *controller_resources
    identityResources:
      cpu: *controller_resources_cpu
      memory:
        limit: 250Mi
        request: 10Mi
    heartbeatResources: *controller_resources
    proxyInjectorResources: *controller_resources
    webhookFailurePolicy: Fail
    spValidatorResources: *controller_resources

  valuesFrom:
  - kind: Secret
    name: linkerd-identity
    valuesKey: identityTrustAnchorsPEM
    targetPath: identityTrustAnchorsPEM
  - kind: Secret
    name: linkerd-identity
    valuesKey: identity.issuer.tls.crtPEM
    targetPath: identity.issuer.tls.crtPEM
  - kind: Secret
    name: linkerd-identity
    valuesKey: identity.issuer.tls.keyPEM
    targetPath: identity.issuer.tls.keyPEM
  - kind: Secret
    name: linkerd-identity
    valuesKey: identity.issuer.crtExpiry
    targetPath: identity.issuer.crtExpiry
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
spec:
  chart:
    spec:
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  interval: 1h
  targetNamespace: linkerd-viz
  values:
    namespace: linkerd-viz
    installNamespace: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-jaeger
  namespace: linkerd-jaeger
spec:
  chart:
    spec:
      chart: linkerd-jaeger
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  interval: 1h
  targetNamespace: linkerd-jaeger
  values:
    namespace: linkerd-jaeger
    installNamespace: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: linkerd
spec:
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
  interval: 1h
  targetNamespace: linkerd
  values:
    namespace: linkerd
    crd:
      create: false
    meshProvider: linkerd
    metricsServer: "http://prometheus.linkerd-viz.svc.cluster.local:9090"
    