---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weatherdrop
  namespace: weatherdrop
spec:
  chart:
    spec:
      chart: weatherdrop
      version: 0.x.x
      sourceRef:
        kind: HelmRepository
        name: bsord
        namespace: flux-system
  interval: 2m
  targetNamespace: weatherdrop
  values:
    existingSecret: weatherdropsecret
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
      targetCPUUtilizationPercentage: 75
    resources:
      requests:
        cpu: 20m
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: weatherdrop-weatherdrop
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
    ingress:
      enabled: true
      existingSecret: weatherdropsecret
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;

          if ($host = "$scheme://www.weatherdrop.io") {
              return 308 https://weatherdrop.io$request_uri;
          }
          if ($host = "http://weatherdrop.io") {
              return 308 https://weatherdrop.io$request_uri;
          }
      hosts:
        - host: weatherdrop.io
          paths:
            - "/" 
        - host: www.weatherdrop.io
          paths:
            - "/"