apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: weatherdropsecret
  namespace: weatherdrop
spec:
  encryptedData:
    giphyApiKey: AgBr8DC4DdvT9aRiRdelyivpcjG7XPZsuCVVNrayoR5TuckOMB4co2Z0XqOruFMkHu97Hd1JLHTHlGpo822YS+MH85Wq+dbzHGogsknrOYNykZjRz1MmJ8r+hmwPSP47iuX3K14O0Tf61VGrV1mamaIEJsst6v5YwqvWOIyYFfceaOm6N3g3/TNXxBK9E2sgqeCrDsfqlp5JVJHUKd+IXtcEWCB1haxFqCusncwzprui8+Nzq356W+qVNOo5ZVPz3+QqbohcWcjau3N3JEZbiFF5OSX4FnIk+dx2J1FmfECPnuDyY30hEeuk8qycN59j8JNfDlAGK6owWItuZIclhOV/AUxwyU1fuOrGOvkXQ6rtagq0/01MN+gH7kk0E1eEuuq2pL2/h/xRn5ILjF93M4sgDtPIpkzR7ZMB6/JOmZYZLy2s1crsd4J3VEvwYRVwypLwdzuJuwh5ePzWc9H2ZTAJLE/rL77FFfSIomNAfGd+xRXIO3jPTlvxK3/mU7OhMNmyErHnVEcGRr1K21DyV3GLy327IWLMeFfh+fAAK7jjfrdZbT52BVEzvLdk5mH3+XUbwYL2b9vQKzF5T+d3yWY51rCZ7b+bA7XHMebX1/Hmz70HPAfvfpbl0HWHL1D4NVDcQYGYcbmzQbpYiQEiVL99WlTCClRZ7pejEexasLm7ZDljGd+9T8qMwlfvysKO4/nQc4FoMDlfAPMPUiD8qtCb0fUmf+4Daq05c5acfn/wgQ==
    openWeatherApiKey: AgCRKgzYxEADOMBSftqakEY+sb7vEqwGoeWzmakLaHUy2s7eq9OfPz7lZvy4r2125TqfWSezbT1TesE6dJOk54+RLlWlfNeTm0rc2jOQcyrh7O1o2P4rxpYOYiFrT9i10S2Bq3fnXbBYTr2+LZwu2+G4CyR7c1tBhuqRNjL7MJr7luvzwbljjslfMKOTJGoY20cNGmrUf1jTIXV70WfwrrSyVivnmPu7/fI8IjJ71SOuZj4VENigcz+1aIqq4gfYkRN2lv31FlQ/A4/59JiwA81cxdNiTUR1Zpfpa6MxEyP/q+uI0aACR5fq/4xkVva8UMwIGniKW4uDNqab+k9U5jhPySj+VABZOO/bgvqRd6XjQLfbAZHTC46OE1phkMbabaCzOaTSFqzTQClm2r+KR+uG0B4sRTeVlfDfywqmMBqWajNNgxQY2Uu471NFZyTz1CvnVG0fCJ77nVwKnlox3jr5CVnfG5bTGQhTOHdzyNqLU4sQOq0OILnTZSeLs6GvU3ZEL9WQgio/Dba7JGtNBi+x/F1ZiTZg4TrL9v9274cZjoxdym1lymw0hnjVUSzo4VBKkdX6lq5Uk0KTqywlD5/ZcgPi/wB8yNTjjz0pzmfwlZC/S/n5m2CDTvIhVa8T3AH5865pCklQjKqYHQUIk7Ua2vzMnvzg/Zkvc8ohFg4ZnHoga23H3MSu0Piwwk4gR7kQquUjJDZXDUQS2xBG6vPnOAQpgnqg9kBtoeNKLiTxig==
  template:
    metadata:
      creationTimestamp: null
      name: weatherdropsecret
      namespace: weatherdrop
status: {}