---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: openfaas
spec:
  releaseName: openfaas
  chart:
    spec:
      chart: openfaas
      version: 5.4.x
      sourceRef:
        kind: HelmRepository
        name: openfaas
        namespace: flux-system
  interval: 30s
  values:
    generateBasicAuth: true
    functionNamespace: openfaas-fn
    serviceType: LoadBalancer
    operator:
      create: true
    queueWorker:
      replicas: 2