apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bsord-homepage
  namespace: bsord-homepage
spec:
  chart:
    spec:
      version: "0.3.0"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - bsord.dev
