---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  interval: 1h
  targetNamespace: falco
  values:
    falcosidekick:
      enabled: true
      webui:
        enabled: true
    falco:
      enabled: true
      syscallEventDrops:
        actions:
          - ignore
      customRules:
        rules-flux.yaml: |-
          - macro: user_known_contact_k8s_api_server_activities
            condition: conatiner.image.repository = "ghcr.io/fluxcd/kustomize-controller"
  valuesFrom:
  - kind: Secret
    name: "falco-values"

      
