---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  interval: 24h
  targetNamespace: falco
  values:
    auditLog:
      enabled: true
    falcosidekick:
      enabled: true
      webui:
        enabled: true
    falco:
      enabled: false
      syscallEventDrops:
        actions:
          - log
      logStderr: true
      logSyslog: false
    customRules:
      custom-rules.yaml: |-
        - list: user_known_k8s_images
          append: true
          items: ["ghcr.io/fluxcd/kustomize-controller", "docker.io/fluxcd/flux", "cr.l5d.io/linkerd/controller"]
        - macro: user_known_contact_k8s_api_server_activities
          condition: container.image.repository in (user_known_k8s_images)
        - list: user_known_sensitive_mount_images
          items: ["docker.io/digitalocean/do-agent", "docker.io/digitalocean/do-csi-plugin", "gcr.io/datadoghq/agent"]
        - macro: user_sensitive_mount_containers
          condition: container.image.repository in (user_known_sensitive_mount_images)
        - macro: user_expected_system_procs_network_activity_conditions
          condition: container.image.repository = "docker.io/bitnami/redis" and proc.cmdline contains "ping"
  valuesFrom:
  - kind: Secret
    name: "falco-values"
          

      
