---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  interval: 1h
  targetNamespace: falco
  values:
    auditLog:
      enabled: true
    falcosidekick:
      enabled: true
      webui:
        enabled: true
    falco:
      enabled: true
      syscallEventDrops:
        actions:
          - ignore
    customRules:
      custom-rules.yaml: |-
        - list: user_known_k8s_images
          append: true
          items: ["ghcr.io/fluxcd/kustomize-controller", "docker.io/fluxcd/flux", "cr.l5d.io/linkerd/controller", "docker.io/digitalocean/do-agent", "docker.io/digitalocean/do-csi-plugin"]
        - macro: user_known_contact_k8s_api_server_activities
          condition: container.image.repository in (user_known_k8s_images)
        - list: user_known_sensitive_mount_images
          append: true
          items: ["docker.io/digitalocean/do-agent", "docker.io/digitalocean/do-csi-plugin"]
        - macro: user_sensitive_mount_containers
          condition: container.image.repository in (user_known_sensitive_mount_images)

      
