---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  interval: 1h
  targetNamespace: falco
  values:
    falcosidekick:
      enabled: true
      webui:
        enabled: true
    falco:
      enabled: true
      syscallEventDrops:
        actions:
          - ignore
      programOutput:
        enabled: true
        keepAlive: false
        #program: mail -s "Falco Notification" someone@example.com
        program: |
          jq 'if .priority == "Emergency" or .priority == "Critical" or .priority == "Error" then
            { attachments: [{ text: .output, color: "danger" }]}
          elif .priority == "Warning" or .priority == "Notice" then
            { attachments: [{ text: .output, color: "warning" }]}
          elif .priority == "Informational" then
            { attachments: [{ text: .output, color: "good" }]}
          else
            { attachments: [{ text: .output }]}
          end' | curl -d @- -X POST https://hooks.slack.com/services/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
      customRules:
        rules-flux.yaml: |-
          - macro: user_known_contact_k8s_api_server_activities
            condition: conatiner.image.repository = "ghcr.io/fluxcd/kustomize-controller"

      
