
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stonks-web
  namespace: stonks
spec:
  chart:
    spec:
      chart: f5-web
      version: 1.1.x
      sourceRef:
        kind: HelmRepository
        name: jonfairbanks
        namespace: flux-system
  dependsOn:
    - name: stonks-api
  interval: 30s
  targetNamespace: stonks
  values:
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
    resources:
      requests:
        cpu: 10m
    f5:
      secretName: "stonks-values"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      hosts:
        - host: stonks.bsord.io
          paths:
            - "/"
