---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: f5-api-wsb
  namespace: stonks
spec:
  chart:
    spec:
      chart: f5-api
      sourceRef:
        kind: HelmRepository
        name: jonfairbanks
        namespace: flux-system
  interval: 30s
  targetNamespace: stonks
  values:
    f5:
      subreddit: "wallstreetbets"
      secretName: "f5-mongouri"
  valuesFrom:
  - kind: Secret
    name: "stonks-values"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: f5-api-gme
  namespace: stonks
spec:
  chart:
    spec:
      chart: f5-api
      sourceRef:
        kind: HelmRepository
        name: jonfairbanks
        namespace: flux-system
  interval: 30s
  targetNamespace: stonks
  values:
    f5:
      subreddit: "gme"
      secretName: "f5-mongouri"
  valuesFrom:
  - kind: Secret
    name: "stonks-values"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: f5-api-superstonk
  namespace: stonks
spec:
  chart:
    spec:
      chart: f5-api
      sourceRef:
        kind: HelmRepository
        name: jonfairbanks
        namespace: flux-system
  interval: 30s
  targetNamespace: stonks
  values:
    f5:
      subreddit: "superstonk"
      secretName: "f5-mongouri"
  valuesFrom:
  - kind: Secret
    name: "stonks-values"