---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stonks-api
  namespace: stonks
spec:
  chart:
    spec:
      chart: f5-api
      version: 1.6.x
      sourceRef:
        kind: HelmRepository
        name: jonfairbanks
        namespace: flux-system
  interval: 30s
  targetNamespace: stonks
  values:
    replicas: 1
    minAvailable: 1
    autoscaling:
      enabled: false
    resources:
      requests:
        cpu: 50m
    image:
      tag: 1.6.18
    f5:
      createSecret: false
      secretName: "f5-mongouri-secret"
      subreddit: superstonk
