
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: f5-web
  namespace: stonks
spec:
  chart:
    spec:
      chart: f5-web
      sourceRef:
        kind: HelmRepository
        name: jonfairbanks
        namespace: flux-system
  dependsOn:
    - name: f5-api-wsb
  interval: 30s
  targetNamespace: stonks
  values:
    f5:
      secretName: "f5-mongouri-secret"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: stonks.bsord.io
          paths:
            - "/"
    podAnnotations:
      linkerd.io/inject: enabled