apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bsord-homepage
  namespace: bsord-homepage
spec:
  releaseName: bsord-homepage
  chart:
    spec:
      chart: bsord-homepage
      sourceRef:
        kind: HelmRepository
        name: bsord
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      path: "/"
    
