---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bsord-homepage
  namespace: flux-system
spec:
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: bsord-homepage
  interval: 30s
  targetNamespace: default
  values:
    replicas: 1